apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-image-0
spec:
  selector:
    matchLabels:
      app: producer-image-0
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-image-0
    spec:
      containers:
        - name: producer-image-0
          image: rysiekp/producer
          env:
            - name: host
              value: my-cluster-kafka-bootstrap:9092
            - name: max_idx
              value: "3"
            - name: idx
              value: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-image-1
spec:
  selector:
    matchLabels:
      app: producer-image-1
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-image-1
    spec:
      containers:
        - name: producer-image-1
          image: rysiekp/producer
          env:
            - name: host
              value: my-cluster-kafka-bootstrap:9092
            - name: max_idx
              value: "3"
            - name: idx
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-image-2
spec:
  selector:
    matchLabels:
      app: producer-image-2
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-image-2
    spec:
      containers:
        - name: producer-image-2
          image: rysiekp/producer
          env:
            - name: host
              value: my-cluster-kafka-bootstrap:9092
            - name: max_idx
              value: "3"
            - name: idx
              value: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-image-0
spec:
  selector:
    matchLabels:
      app: consumer-image-0
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-image-0
    spec:
      containers:
        - name: consumer-image-0
          image: rysiekp/consumer
          env:
            - name: host
              value: my-cluster-kafka-bootstrap:9092
            - name: topics
              value: "warm,cold"
            - name: poll_interval
              value: "20"
            - name: max_poll_records
              value: "1"
            - name: consumer_group
              value: "group1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-image-1
spec:
  selector:
    matchLabels:
      app: consumer-image-1
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-image-1
    spec:
      containers:
        - name: consumer-image-1
          image: rysiekp/consumer
          env:
            - name: host
              value: my-cluster-kafka-bootstrap:9092
            - name: topics
              value: "light,cold"
            - name: poll_interval
              value: "20"
            - name: max_poll_records
              value: "1"
            - name: consumer_group
              value: "group2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-image-2
spec:
  selector:
    matchLabels:
      app: consumer-image-2
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-image-2
    spec:
      containers:
        - name: consumer-image-2
          image: rysiekp/consumer
          env:
            - name: host
              value: my-cluster-kafka-bootstrap:9092
            - name: topics
              value: "dark"
            - name: poll_interval
              value: "20"
            - name: max_poll_records
              value: "1"
            - name: consumer_group
              value: "group3"

